# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/stepmotor.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/Dir-Dur.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/LFSR.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/Register.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/SevSeg_4digit.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/Mapper.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/keypad4X4.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/steppermotor_wrapper.sv
  D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/sources_1/new/MyMain.sv
}
read_xdc D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/constrs_1/new/Cons.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS/Desktop/Projem/Projem/Projem.srcs/constrs_1/new/Cons.xdc]

synth_design -top MyMain -part xc7a35tcpg236-1
write_checkpoint -noxdef MyMain.dcp
catch { report_utilization -file MyMain_utilization_synth.rpt -pb MyMain_utilization_synth.pb }
